services:
  archisteamfarm:
    image: justarchi/archisteamfarm:6.2.2.3
    container_name: archisteamfarm
    # Перезапускать контейнер, если он остановится, если только он не был остановлен явно
    restart: unless-stopped
    # Монтирование локальной папки в папку конфигурации контейнера
    # ВАЖНО: Замените './config' на абсолютный путь к вашей локальной папке конфигурации ASF.
    # Эта папка должна содержать ваши файлы ASF.json и JSON-файлы ботов.
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
    # Опционально: Откройте порт IPC, если планируете использовать веб-интерфейс (ASF-IPC)
    # Порт по умолчанию — 1242.
    ports:
      # Привязка к IPv4 localhost
      - "1242:1242"
    # Опционально: Установите часовой пояс для корректного логирования и планирования
    environment:
      - TZ=Europe/Moscow
    # Опционально: Установите конкретный ID пользователя/группы для разрешений томов
    # user: "1000:1000"
